const functionsBase = import.meta.env.VITE_NETLIFY_FUNCTIONS_BASE || '/.netlify/functions';
const orderPlacedUrl = `${functionsBase}/order-placed`;
const orderPickedUrl = `${functionsBase}/order-picked`;
const orderDispatchedUrl = `${functionsBase}/order-dispatched`;

const postWebhook = async (url: string, payload: Record<string, unknown>, context: string) => {
  console.log(`[notify] Calling ${context} at:`, url);
  console.log(`[notify] Payload:`, payload);

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
      // Add timeout to prevent hanging
      signal: AbortSignal.timeout(30000), // 30 second timeout
    });

    console.log(`[notify] Response status:`, response.status);

    if (!response.ok) {
      const errorText = await response.text().catch(() => '');
      console.error(`[notify] Error response:`, errorText);
      throw new Error(`${context} notification failed with status ${response.status} ${response.statusText}${errorText ? `: ${errorText}` : ''}`);
    }

    const responseData = await response.json().catch(() => null);
    console.log(`[notify] Success response:`, responseData);

    return responseData;
  } catch (error) {
    console.error(`[notify] Call failed:`, error);

    if (error instanceof Error) {
      if (error.name === 'TypeError' && error.message.includes('fetch')) {
        throw new Error(`Failed to reach ${context} notification at ${url}.`);
      }
      throw error;
    }

    throw new Error(`Unexpected error calling ${context} notification`);
  }
};

export type OrderFormDataSnapshot = {
  dateOrdered: string;
  dateOrderedISO: string;
  itemCategory: string;
  itemNature: string;
  deliveryParty: string;
  orderedBy: string;
  contractorCompany: string | null;
  region: string | null;
  technician: string | null;
  orderLocation: string | null;
  popId: string | null;
  recipientName: string | null;
  recipientCompanyName: string | null;
  recipientAddress: string | null;
  recipientContactNumber: string | null;
  recipientEmail: string | null;
  cellPhoneNumber: string | null;
};

export type CartItemSnapshot = {
  id: string;
  itemName: string;
  itemDescription: string;
  itemCategory: string;
  itemNature: string;
  quantity: number;
  itemUrl: string | null;
};

export interface OrderLineWebhookPayload {
  orderId: string;
  autoGeneratedOrderId: number;
  uniqueOrderRecordId: string;
  dateOrdered: string;
  dateOrderedISO: string;
  totalQuantity: number;
  lineNumber: number;
  cartLength: number;
  itemCategory: string;
  itemNature: string;
  deviceType: string;
  itemId: string;
  itemDescription: string;
  quantityOrdered: number;
  itemUrl: string | null;
  contractorCompany: string | null;
  region: string | null;
  technician: string | null;
  orderedBy: string;
  orderLocation: string | null;
  deliverToPart: string;
  popId: string | null;
  recipientName: string | null;
  recipientCompanyName: string | null;
  recipientAddress: string | null;
  recipientContactNumber: string | null;
  recipientEmail: string | null;
  cellPhoneNumber: string | null;
  formData: OrderFormDataSnapshot;
  cartItem: CartItemSnapshot;
  [key: string]: unknown;
}

export interface OrderPlacedWebhookPayload {
  orderId: string;
  autoGeneratedOrderId: number;
  uniqueOrderRecordId: string;
  totalItems: number;
  totalQuantity: number;
  dateOrdered: string;
  dateOrderedISO: string;
  orderedBy: string;
  deliveryParty: string;
  contractorCompany: string | null;
  region: string | null;
  formData: OrderFormDataSnapshot;
  cartItems: CartItemSnapshot[];
  lineItems?: OrderLineWebhookPayload[]; // Full line item data for n8n to create Stock_Order records
  items: Array<{
    deviceType: string;
    quantityOrdered: number;
    itemUrl: string | null;
    itemDescription: string;
    itemCategory: string;
    itemNature: string;
    itemId: string;
  }>;
  [key: string]: unknown;
}

export interface OrderStageUnitPayload {
  unitId: string;
  lineItemId?: string;
  unitIndex: number;
  totalUnits: number;
  serialNumber: string | null;
  isSerialised: boolean;
  deviceType?: string;
  itemCode?: string;
}

export interface OrderStageWebhookPayload {
  orderId: string;
  uniqueOrderRecordId: string;
  autoGeneratedOrderId?: number;
  dateOrdered?: string;
  dateOrderedISO?: string;
  totalItems?: number;
  totalQuantity?: number;
  items: Array<{
    deviceType: string;
    quantityOrdered?: number;
    itemUrl?: string | null;
    itemDescription?: string;
    itemCategory?: string;
    itemNature?: string;
    itemId?: string;
    itemCode?: string;
    serialNumbers?: string[];
    units?: OrderStageUnitPayload[];
  }>;
  orderedBy?: string | null;
  deliveryParty?: string | null;
  contractorCompany?: string | null;
  region?: string | null;
  technician?: string | null;
  orderLocation?: string | null;
  recipientName?: string | null;
  recipientCompanyName?: string | null;
  recipientAddress?: string | null;
  recipientContactNumber?: string | null;
  recipientEmail?: string | null;
  cellPhoneNumber?: string | null;
  warehouseFulfilling?: string | null;
  deliverToParty?: string | null;
  formData?: OrderFormDataSnapshot;
  cartItems?: CartItemSnapshot[];
  metadata?: Record<string, unknown>;
  [key: string]: unknown;
}

const assertConfigured = (url: string | undefined, name: string) => {
  if (!url || url.trim().length === 0) {
    throw new Error(`Missing ${name} configuration.`);
  }
  return url;
};

export const n8nService = {
  async submitOrderLine(payload: OrderLineWebhookPayload) {
    await postWebhook(orderPlacedUrl, payload, 'order line submission');
  },

  async notifyOrderPlaced(payload: OrderPlacedWebhookPayload) {
    await postWebhook(orderPlacedUrl, payload, 'order placed');
  },

  async notifyOrderPicked(payload: OrderStageWebhookPayload) {
    await postWebhook(orderPickedUrl, payload, 'order picked');
  },

  async notifyOrderDispatched(payload: OrderStageWebhookPayload) {
    await postWebhook(orderDispatchedUrl, payload, 'order dispatched');
  },

  async notifyOrderManifest(payload: OrderStageWebhookPayload) {
    await postWebhook(orderDispatchedUrl, payload, 'order manifest');
  },

  async chatWithAssistant(message: string) {
    const url = assertConfigured(import.meta.env.VITE_N8N_CHAT_WEBHOOK_URL, 'VITE_N8N_CHAT_WEBHOOK_URL');
    
    return await postWebhook(url, { message }, 'chat assistant');
  }
};
