const submitOrderWebhookUrl = import.meta.env.VITE_N8N_SUBMIT_ORDER_WEBHOOK_URL;
const orderPlacedWebhookUrl = import.meta.env.VITE_N8N_ORDER_PLACED_WEBHOOK_URL;
const orderPickedWebhookUrl = import.meta.env.VITE_N8N_ORDER_PICKED_WEBHOOK_URL ?? 'http://localhost:5678/webhook-test/a02fb1f6-4a82-45cf-95ba-c834c7f33772';
const orderDispatchedWebhookUrl = import.meta.env.VITE_N8N_ORDER_DISPATCHED_WEBHOOK_URL ?? 'http://localhost:5678/webhook-test/2bd2d581-51d5-4f97-9a3d-cdf2c764a768';
const orderManifestWebhookUrl = import.meta.env.VITE_N8N_ORDER_MANIFEST_WEBHOOK_URL ?? 'http://localhost:5678/webhook-test/63abdb10-c749-4046-ac8d-4686dd813b17';

const assertWebhookConfigured = (url: string | undefined, name: string) => {
  if (!url || url.trim().length === 0) {
    throw new Error(`Missing ${name} configuration. Please set the ${name} environment variable.`);
  }

  return url;
};

const postWebhook = async (url: string, payload: Record<string, unknown>, context: string) => {
  console.log(`[n8n] Calling ${context} webhook at:`, url);
  console.log(`[n8n] Payload:`, payload);
  
  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
      // Add timeout to prevent hanging
      signal: AbortSignal.timeout(30000), // 30 second timeout
    });

    console.log(`[n8n] Response status:`, response.status);

    if (!response.ok) {
      const errorText = await response.text().catch(() => '');
      console.error(`[n8n] Webhook error response:`, errorText);
      throw new Error(`n8n ${context} webhook failed with status ${response.status} ${response.statusText}${errorText ? `: ${errorText}` : ''}`);
    }
    
    const responseData = await response.json().catch(() => null);
    console.log(`[n8n] Success response:`, responseData);
    
    return responseData;
  } catch (error) {
    console.error(`[n8n] Webhook call failed:`, error);
    
    if (error instanceof Error) {
      // Enhance error message for common issues
      if (error.name === 'TypeError' && error.message.includes('fetch')) {
        throw new Error(`Failed to connect to n8n webhook at ${url}. Please check:\n1. The webhook URL is correct\n2. n8n is running and accessible\n3. CORS is configured if needed`);
      }
      throw error;
    }

    throw new Error(`Unexpected error calling n8n ${context} webhook`);
  }
};

export type OrderFormDataSnapshot = {
  dateOrdered: string;
  dateOrderedISO: string;
  itemCategory: string;
  itemNature: string;
  deliveryParty: string;
  orderedBy: string;
  contractorCompany: string | null;
  region: string | null;
  technician: string | null;
  orderLocation: string | null;
  popId: string | null;
  recipientName: string | null;
  recipientCompanyName: string | null;
  recipientAddress: string | null;
  recipientContactNumber: string | null;
  recipientEmail: string | null;
  cellPhoneNumber: string | null;
};

export type CartItemSnapshot = {
  id: string;
  itemName: string;
  itemDescription: string;
  itemCategory: string;
  itemNature: string;
  quantity: number;
  itemUrl: string | null;
};

export interface OrderLineWebhookPayload {
  orderId: string;
  autoGeneratedOrderId: number;
  uniqueOrderRecordId: string;
  dateOrdered: string;
  dateOrderedISO: string;
  totalQuantity: number;
  lineNumber: number;
  cartLength: number;
  itemCategory: string;
  itemNature: string;
  deviceType: string;
  itemId: string;
  itemDescription: string;
  quantityOrdered: number;
  itemUrl: string | null;
  contractorCompany: string | null;
  region: string | null;
  technician: string | null;
  orderedBy: string;
  orderLocation: string | null;
  deliverToPart: string;
  popId: string | null;
  recipientName: string | null;
  recipientCompanyName: string | null;
  recipientAddress: string | null;
  recipientContactNumber: string | null;
  recipientEmail: string | null;
  cellPhoneNumber: string | null;
  formData: OrderFormDataSnapshot;
  cartItem: CartItemSnapshot;
  [key: string]: unknown;
}

export interface OrderPlacedWebhookPayload {
  orderId: string;
  autoGeneratedOrderId: number;
  uniqueOrderRecordId: string;
  totalItems: number;
  totalQuantity: number;
  dateOrdered: string;
  dateOrderedISO: string;
  orderedBy: string;
  deliveryParty: string;
  contractorCompany: string | null;
  region: string | null;
  formData: OrderFormDataSnapshot;
  cartItems: CartItemSnapshot[];
  lineItems?: OrderLineWebhookPayload[]; // Full line item data for n8n to create Stock_Order records
  items: Array<{
    deviceType: string;
    quantityOrdered: number;
    itemUrl: string | null;
    itemDescription: string;
    itemCategory: string;
    itemNature: string;
    itemId: string;
  }>;
  [key: string]: unknown;
}

export interface OrderStageUnitPayload {
  unitId: string;
  lineItemId?: string;
  unitIndex: number;
  totalUnits: number;
  serialNumber: string | null;
  isSerialised: boolean;
  deviceType?: string;
  itemCode?: string;
}

export interface OrderStageWebhookPayload {
  orderId: string;
  uniqueOrderRecordId: string;
  autoGeneratedOrderId?: number;
  dateOrdered?: string;
  dateOrderedISO?: string;
  totalItems?: number;
  totalQuantity?: number;
  items: Array<{
    deviceType: string;
    quantityOrdered?: number;
    itemUrl?: string | null;
    itemDescription?: string;
    itemCategory?: string;
    itemNature?: string;
    itemId?: string;
    itemCode?: string;
    serialNumbers?: string[];
    units?: OrderStageUnitPayload[];
  }>;
  orderedBy?: string | null;
  deliveryParty?: string | null;
  contractorCompany?: string | null;
  region?: string | null;
  technician?: string | null;
  orderLocation?: string | null;
  recipientName?: string | null;
  recipientCompanyName?: string | null;
  recipientAddress?: string | null;
  recipientContactNumber?: string | null;
  recipientEmail?: string | null;
  cellPhoneNumber?: string | null;
  warehouseFulfilling?: string | null;
  deliverToParty?: string | null;
  formData?: OrderFormDataSnapshot;
  cartItems?: CartItemSnapshot[];
  metadata?: Record<string, unknown>;
  [key: string]: unknown;
}

export const n8nService = {
  async submitOrderLine(payload: OrderLineWebhookPayload) {
    const url = assertWebhookConfigured(submitOrderWebhookUrl, 'VITE_N8N_SUBMIT_ORDER_WEBHOOK_URL');
    await postWebhook(url, payload, 'order line submission');
  },

  async notifyOrderPlaced(payload: OrderPlacedWebhookPayload) {
    const url = assertWebhookConfigured(orderPlacedWebhookUrl, 'VITE_N8N_ORDER_PLACED_WEBHOOK_URL');
    await postWebhook(url, payload, 'order placed notification');
  },

  async notifyOrderPicked(payload: OrderStageWebhookPayload) {
    const url = assertWebhookConfigured(orderPickedWebhookUrl, 'VITE_N8N_ORDER_PICKED_WEBHOOK_URL');
    await postWebhook(url, payload, 'order picked notification');
  },

  async notifyOrderDispatched(payload: OrderStageWebhookPayload) {
    const url = assertWebhookConfigured(orderDispatchedWebhookUrl, 'VITE_N8N_ORDER_DISPATCHED_WEBHOOK_URL');
    await postWebhook(url, payload, 'order dispatched notification');
  },

  async notifyOrderManifest(payload: OrderStageWebhookPayload) {
    const url = assertWebhookConfigured(orderManifestWebhookUrl, 'VITE_N8N_ORDER_MANIFEST_WEBHOOK_URL');
    await postWebhook(url, payload, 'order manifest notification');
  }
,
  async chatWithAssistant(message: string) {
    // You will need to add this variable to your .env file
    // VITE_N8N_CHAT_WEBHOOK_URL=https://[your-n8n-url]/webhook/chat
    const url = assertWebhookConfigured(import.meta.env.VITE_N8N_CHAT_WEBHOOK_URL, 'VITE_N8N_CHAT_WEBHOOK_URL');
    
    return await postWebhook(url, { message }, 'chat assistant');
  }
};
